---
# vars file for oracle rac

oracle_major_version: "19"

oracle_install_package_names: ["db_home_2020-02-29_11-53-10PM.zip"]

oracle_ver_path: "19.5.0.0"

oracle_sid: "TEST19C"

oracle_home: "/oracle/u01/db/{{ oracle_ver_path }}"

