---
# tasks file for oraclebase

- debug: var=ansible_memory_mb
- debug: msg="total RAM is {{ ansible_memory_mb.real.total }} required 4096M "
- fail: msg="not enough RAM"
  when: ansible_memory_mb.real.total < 4096

- debug: msg="MEM {{ mem }}"
- debug: msg="SHMA {{ shma }}"
- debug: msg="SHMM {{ shmm }}"

- name: tuned oracle dir
  file:
    path: /usr/lib/tuned/oracle/
    state: directory
    recurse: yes

- name: tuned.conf
  copy:
    src: tuned.conf
    dest: /usr/lib/tuned/oracle/tuned.conf

- name: oracle .rpms
  yum:
    name: glibc-devel,libstdc++-devel,compat-libcap1,libaio-devel,libXtst,perl-Data-Dumper,unzip,libXrender,compat-libstdc++-33,bc,net-tools
    state: latest

- include: sysctl.yml

- name: stop firewall
  systemd:
    name: firewalld.service
    state: stopped
    enabled: no

- name: Ensure group "oinstall" exists
  group:
    name: oinstall
    gid: 800

- name: Ensure group "dba" exists
  group:
    name: dba
    gid: 801

- name: Ensure group "oper" exists
  group:
    name: oper
    gid: 802

- name: Ensure group "asmadmin" exists
  group:
    name: asmadmin
    gid: 803

- name: Ensure group "asmdba" exists
  group:
    name: asmdba
    gid: 804

- name: Ensure group "asmoper" exists
  group:
    name: asmoper
    gid: 805

- name: Add the user "oracle"
  user:
    name: oracle
    shell: /bin/bash
    uid: 800
    group: oinstall
    comment: "Oracle instalation owner"
    groups: oinstall,dba,oper,asmadmin,asmdba,asmoper
    append: yes
    system: yes
    password: '$6$a5MJYlNAPSevwLhh$m1EJvszxPAMkwumqCQcHS07fLyLPYTWUyPFR7K58hghtDyiSL0GF.svFSA8f7MxkBXUx8uTczpPIJKrb1O14h'

- user: 
    name: oracle
    # python -c 'import crypt; print crypt.crypt("acror", "$1$SomeSalt$")'
    password: "$1$SomeSalt$V2yJBnrIRWQytrgM9BB2Y1"

- name: Add the user "oracle" keys (1)
  authorized_key:
    user: oracle
    key: '{{ item }}'
  with_file:
    - autorized_keys.thinkpad

- name: Oracle sudo
  copy:
    src: sudoerrs
    dest: /etc/sudoers.d/oracle
    mode: '0440'

- name: Oracle CRS/Restart required packages
  yum: 
    name=device-mapper-multipath,ksh,sysstat,smartmontools,gcc-c++
    state=latest

- name: Oracle CRS/Restart required packages
  yum: 
    name=cvuqdisk
    state=latest
    disable_gpg_check=yes 

- name: Create a logical volume u01
  lvol:
    vg: vg01
    lv: u01
    size: 80%VG
    shrink: no

- name: Create /dev/vg01/u01
  filesystem:
    fstype: ext4
    dev: /dev/vg01/u01

- name: Mount /dev/vg01/u01
  mount:
    path: /oracle
    src: /dev/vg01/u01
    state: mounted
    fstype: auto

- name: u01 directory
  file:
    path: /oracle/u01
    owner: root
    group: oinstall
    mode: '0775'
    state: directory

- name: "ORACLE_HOME /oracle/u01/gi"
  file:
    path: "/oracle/u01/gi"
    state: directory
    owner: oracle
    group: oinstall
    recurse: yes
    mode: '0775'

- name: "ORACLE_HOME /oracle/u01/db"
  file:
    path: "/oracle/u01/db"
    state: directory
    owner: oracle
    group: oinstall
    recurse: yes
    mode: '0775'

- name: Limits
  copy:
    src: 99-oracle-limits.conf
    dest: /etc/security/limits.d/99-oracle-limits.conf

- name: 'Extend the / (root)'
  lvol:
    vg: vg00
    lv: lv_root
    size: 10g
    shrink: no
    resizefs: yes

- name: 'Extend the /tmp'
  lvol:
    vg: vg00
    lv: lv_tmp
    size: 2g
    shrink: no
    resizefs: yes

- name: 'Extend the u01'
  lvol:
    vg: vg01
    lv: u01
    size: 29G
    shrink: no
    resizefs: yes
