---
- hosts: all
  any_errors_fatal: true
  tasks:
  - name: System details
    debug: msg="{{ item }}"
    with_items: 
    - "{{ ansible_distribution }}"
    - "{{ ansible_distribution_version }}"
    - "{{ ansible_distribution_major_version }}"
  roles:
  - base.host
  - base.oracle
  - oracle.crs.21c
  - oracle.db.home.21c
  - oracle.db.create.21c
  - oracle.post.install
  vars:
    password: Xb6a5ed2ff29f98d
    cluster_name: c19
