
- name: Grid Setup
  block:
    - name: ACFS Centos path
      copy:
        src: acfs.centos.patch
        dest: /oracle/u01/gi/{{ oracle_ver_path }}/lib/

    - name: Apply patch ACFS Centos patch
      patch:
        src: acfs.centos.patch
        basedir: /oracle/u01/gi/{{ oracle_ver_path }}/lib/
        strip: 0

    # This one is done as part of golden image creatinon
    # - name: install grid.rsp
    #   template:
    #     src: grid.phase.0.no.comments.rsp
    #     dest: /home/oracle/grid.phase.0.rsp
    #     mode: '0640'
    #     owner: oracle

    - name: install grid.rsp
      template:
        src: grid.phase.0.no.comments.rsp
        dest: /home/oracle/grid.phase.1.rsp
        mode: '0640'
        owner: oracle
      when: ansible_hostname == first_rac_node

    - name: "gridSetup.sh (part I)"
      shell: "./gridSetup.sh -silent -responseFile /home/oracle/grid.phase.1.rsp"
      args:
        chdir: "/oracle/u01/gi/{{ oracle_ver_path }}"
        creates: "/oracle/u01/oraInventory/oraInst.loc"
      ignore_errors: true
      register: grid_setup_out
    - debug: 
        msg: "gridSetup.sh (part I) {{ grid_setup_out }}"
      when: grid_setup_out.rc >= 2
    - debug: 
        msg: "Return code is {{ grid_setup_out.rc }}"
      when: grid_setup_out.rc >= 2

  # rescue:
  #   - debug:
  #       msg: '"./gridSetup.sh failed'
  #   - name: delete install grid response file
  #     file:
  #       path: /home/oracle/grid.rsp
  #       state: absent

  become: yes
  become_user: oracle
  when: ansible_hostname == first_rac_node

