---
# tasks file for oracle_systemd

- debug:
    var: ansible_default_ipv4.gateway

# on RHEL7 we must use Python2 (package python3-systemd is not present here)
- name: systemd-python
  yum:
    name: systemd-python
  when: ansible_distribution_major_version == '7'

- name: /usr/libexec/oracle_systemd-service
  template:
    src: libexec/oracle-systemd-service.py2
    dest: /usr/libexec/oracle-systemd-service
    mode: 0755
  when: ansible_distribution_major_version == '7'

# on RHEL8 we must use Python3
- name: python3-systemd
  yum:
    name: python3-systemd
  when: ansible_distribution_major_version == '8'

- name: /usr/libexec/oracle_systemd-service
  template:
    src: libexec/oracle-systemd-service.py3
    dest: /usr/libexec/oracle-systemd-service
    mode: 0755
  when: ansible_distribution_major_version == '8'
  
# This only one file has template in it
- name: /etc/sysconfig/network-reachable
  template:
    src: sysconfig/network-reachable
    dest: /etc/sysconfig/network-reachable

- name: "Ivan's Profile files"
  # copy:
  #   src:  "{{ item.file_name }}"
  #   dest: "{{ item.dest }}"
  #   mode: "{{ item.mode | default('0644') }}"
  #   directory_mode: "{{ item.mode | default('no') }}"
  debug:
    msg: "{{ item.file_name }} => {{ item.dest }}"
  with_items:
    - file_name: oracle-systemd-scripts/systemd/network-reachable.service
      dest: /etc/systemd/system/network-reachable.service      
    - file_name: oracle-systemd-scripts/systemd/oracle.service
      dest: /etc/systemd/system/oracle.service

    # installed via template
    #- file_name: oracle-systemd-scripts/sysconfig/network-reachable
    #  dest: /etc/systemd/system/network-reachable
    - file_name: oracle-systemd-scripts/sysconfig/oracle
      dest: /etc/systemd/sysconfig/oracle

    - file_name: oracle-systemd-scripts/libexec/network-reachable
      dest: /usr/libexec/network-reachable
      mode: 0755
    # - file_name: libexec/oracle-systemd-service.py3
    #   dest: /usr/libexec/oracle-systemd-service
    #   mode: 0755

    - file_name: oracle-systemd-scripts/site-packages/dotora
      dest: /usr/lib/python2.7/site-packages/dotora
      directory_mode: yes
      
- name: systemd daemon-reload
  systemd: 
    name=network-reachable
    daemon_reload=yes

- name: systemd daemon-reload
  systemd: 
    name=oracle
    enabled=yes
    daemon_reload=yes
