
- block:
    - name: Download install package {{ item }}
      get_url:
        url: http://192.168.8.200/oracle/{{ oracle_major_version }}/{{ item }}
        dest: /home/oracle/
        mode: '0640'

    - name: unzip install package {{ item }}
      unarchive:
        src: /home/oracle/{{ item }}
        dest: /home/oracle
        remote_src: yes

    - name: delete install .zip package {{ item }}
      file:
        path: /home/oracle/{{ item }}
        state: absent

  become: yes
  become_user: oracle
