
- name: "Grid Setup runInstaller (part I)"
  block:
    # - name: ACFS Centos path
    #   copy:
    #     src: acfs.centos.patch
    #     dest: /oracle/u01/gi/{{ oracle_ver_path }}/lib/

    # - name: Apply patch ACFS Centos patch
    #   patch:
    #     src: acfs.centos.patch
    #     basedir: /oracle/u01/gi/{{ oracle_ver_path }}/lib/
    #     strip: 0

    - name: install grid.rsp
      template:
        src: grid.no.comments.rsp
        dest: /home/oracle/grid.rsp
        mode: '0640'
        owner: oracle

    # - name: "Gi fome"
    #   file:
    #     path: "/oracle/u01/gi/{{ oracle_ver_path }}"
    #     state: directory
    #     owner: oracle
    #     group: oinstall
    #     recurse: yes
    #     mode: '0755'

    - name: "runInstaller (part I)"
      shell: "./runInstaller -silent -responseFile /home/oracle/grid.rsp -ignoreSysPrereqs -waitforcompletion"
      args:
        chdir: "/home/oracle/grid/"
        creates: "/oracle/u01/oraInventory/oraInst.loc"
      ignore_errors: true
      register: grid_setup_out
    - debug: 
        msg: "runInstaller (part I) {{ grid_setup_out }}"
      when: grid_setup_out.rc >= 0
    - debug: 
        msg: "Return code is {{ grid_setup_out.rc }}"
      when: grid_setup_out.rc >= 0
    - fail:
        msg: "runInstaller (part I) failed"
      when: grid_setup_out.rc > 6

  rescue:
    # - name: delete response file
    #   file:
    #     path: /home/oracle/grid.rsp
    #     state: absent

    - fail:
        msg: '"./runInstaller failed'

  become: yes
  become_user: oracle
  # Condition to be set on caller level
  # when: ansible_hostname == first_rac_node


- name: delete install grid.rsp
  file:
    path: /home/oracle/grid.rsp
    state: absent
