all:
  hosts:
    rac18-a-node-1:
      address: 192.168.8.60
      listener: rac18-a-lis-1
      oracle_release: 18c
      oracle_install_type: rac      
    rac18-a-node-2:
      address: 192.168.8.61
      listener: rac18-a-lis-2
      oracle_release: 18c
      oracle_install_type: rac
  children:
    oracle:
      hosts:
        rac18-a-node-1:
        rac18-a-node-2:
      vars:
  vars:
    scsi:
    - adapter:
        pciSlotNumber: 16
    - adapter:
        pciSlotNumber: 32
    disks:
    - disk: rootdg
      size: 10g
      bus: 0
    - disk: appdg
      size: 100g
      bus: 0
    network:
    - adapter:
      pciSlotNumber: 192
      network: "Public Network"
    - adapter:
      pciSlotNumber: 224
      network: "Barn Network"      
    ram: 16G
    cpu: 2

    vmware:
      vm_folder: VmFolder
      datastore: WD1T

    cluster:
      oracle_cluster_name: rac18c-a
      # A lot of space for GIMR database
      disks:
        - disk:
            size: 16
            bus: 1
            count: 4
      addresses:
        rac18-a-lis-1: 192.168.8.63
        rac18-a-lis-2: 192.168.8.64
        rac18-a-scan: [192.168.8.67, 192.168.8.68, 192.168.8.69]

    scan: rac18-a-scan
    oracle_password: Xb6a5ed2ff29f98d
