all:
  hosts:
    rhel7a-21-restart:
      address: 192.168.8.104
  children:
    oracle:
      hosts:
        rhel7a-21-restart:
      vars:
        oracle-release: 21c
  vars:
    scsi:
    - adapter:
        pciSlotNumber: 16
    - adapter:
        pciSlotNumber: 32
    disks:
    - disk: rootdg
      size: 10g
      bus: 0
    - disk: appdg
      size: 60g
      bus: 0
    network:
    - adapter:
      pciSlotNumber: 192
      network: "Public Network"
    - adapter:
      pciSlotNumber: 224
      network: "Barn Network"      
    ram: 16G
    cpu: 2

    vmware:
      vm_folder: VmFolder
      datastore: WD1T

    cluster:
      clustername: rhel7a-21
      disks:
        - disk:
            size: 8
            bus: 1
            count: 4

    password: Xb6a5ed2ff29f98d
