---
# vars file for oracle.crs.os.setup

# Global variables to be used by further roles

first_rac_node: "{{ ansible_play_batch | sort() | first }}"

play_hosts_sorted: "{{ play_hosts | sort() }}"

crs_node_index: "{{play_hosts_sorted.index(inventory_hostname) + 1 }}"

crs_node_list: []
db_node_list: []
