---

# tasks file for base.host

- name: Clean yum repos
  shell: "yum clean all"
  args:
    warn: false # set warn=false to prevent warning
  changed_when: false

- name: DNS search
  copy:
    src: resolv.conf
    dest: /etc/resolv.conf

- name: "Repo file: {{ item }}"
  copy:
    src: "{{ item }}"
    dest: /etc/yum.repos.d/
  loop:
    - KS_x86_64.repo
    - KS_noarch.repo

- name: Base packages
  yum: 
    name: wget,mlocate,strace,psmisc,nfs-utils,emacs-nox,patch,gcc,xauth,epel-release
    state: latest
    lock_timeout: 160
    disable_gpg_check: yes 
  tags: packages

- name: Create a directory /oinstall
  file:
    path: /oinstall
    state: directory
    mode: '0755'

- name: Mount NFS
  mount:
    path: "/oinstall"
    src: "kicklinux:/var/www/html/oracle"
    fstype: nfs
    opts: ro
    state: mounted

- name: Set authorized key for root
  authorized_key:
    user: root
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/authorized_keys') }}"

- name: 'Extend /var fs'
  lvol:
    vg: vg00
    lv: lv_var
    size: 2G
    shrink: no
    resizefs: yes

- name: Clean yum repos
  shell: "yum clean all"
  args:
    warn: false # set warn=false to prevent warning
  changed_when: false
