
- name: "Grid Setup gridSetup.sh (part I)"
  block:
    - name: ACFS Centos path
      copy:
        src: acfs.centos.patch
        dest: "{{ oracle_home }}/lib/"

    - name: Apply patch ACFS Centos patch
      patch:
        src: acfs.centos.patch
        basedir: "{{ oracle_home }}/lib/"
        strip: 0

    - name: install grid.rsp
      template:
        src: grid.no.comments.rsp
        dest: "{{ oracle_install_dir_temp }}/grid.rsp"
        mode: '0640'
        owner: "{{ oracle_os_user }}"

    - name: "gridSetup.sh (part I)"
      shell: "./gridSetup.sh -silent -responseFile {{ oracle_install_dir_temp }}/grid.rsp"
      args:
        chdir: "{{ oracle_home }}"
        creates: "{{ oracle_inventory_location }}/oraInst.loc"
      ignore_errors: true
      register: grid_setup_out
    - debug: 
        msg: "gridSetup.sh (part I) {{ grid_setup_out }}"
      when: grid_setup_out.rc >= 0
    - debug: 
        msg: "Return code is {{ grid_setup_out.rc }}"
      when: grid_setup_out.rc >= 0
    - fail:
        msg: "./gridSetup.sh -executeConfigTools failed"
      when: grid_setup_out.rc > 6

  become: yes
  become_user: oracle
  # Condition to be set on caller level
  # when: ansible_hostname == first_rac_node
