
# default machine definition
- default:
  name: "Default"
  ram: 6G
  cpu: 1
  scsi:
    - adapter:
        pciSlotNumber: 128
  disks:
    - disk: rootdg
      size: 20g
      bus: 0
    - disk: appdg
      size: 20g
      bus: 0
  network:
    - adapter:
        pciSlotNumber: 192
        network: "Public Network"
    - adapter:
        pciSlotNumber: 224
        network: "Barn Network"
  vmware:
    vm_folder: VmFolder
    datastore: Kingston890G


- machine:
  name: kafka-1
  template: "RHEL7 Template"
  addresses:
    kafka-1: 192.168.8.120
  
- machine:
  name: kafka-2
  template: "RHEL7 Template"
  addresses:
    kafka-2: 192.168.8.121

  