
# default machine definition
- default:
  name: "Default"
  ram: 16G
  cpu: 2
  scsi:
    - adapter:
        pciSlotNumber: 16
    - adapter:
        pciSlotNumber: 32

  disks:
    - disk: rootdg
      size: 10g
      bus: 0
    - disk: appdg
      size: 60g
      bus: 0
  network:
    - adapter:
        pciSlotNumber: 192
        network: "Public Network"
    - adapter:
        pciSlotNumber: 224
        network: "Barn Network"
  vmware:
    vm_folder: VmFolder
    datastore: WD1T


- machine:
  name: rac121-node-1
  template: "RHEL7 Template"
  addresses:
    rac121-node-1: 192.168.8.60

- machine:
  name: rac121-node-2
  template: "RHEL7 Template"
  addresses:
    rac121-node-2: 192.168.8.61

- cluster:
  name: rac121c-a
  nodes: [rac121-a-node-1,rac121-a-node-2]
  disks:
    - disk:
      size: 8
      bus: 1
      count: 4
  addresses:
    rac121-a-lis-1: 192.168.8.63
    rac121-a-lis-2: 192.168.8.64
    rac121-a-scan: [192.168.8.67, 192.168.8.68, 192.168.8.69]
