# oracle database 18c

- name: DB Home Setup
  block:

    - name: DB init parameter undo_tablespace (RAC mode)
      set_fact:
        init_undo_list: "{{ init_undo_list + [ oracle_sid + ((play_hosts.index(item) + 1)|string) + '.undo_tablespace=UNDOTBS' + ((play_hosts.index(item) + 1)|string) ] }}"
      with_items: "{{ ansible_play_batch }}"
      when: first_rac_node is defined

    - name: DB init parameter undo_tablespace (Standalone mode)
      set_fact:
        init_undo_list: "{{ [ oracle_sid + '.undo_tablespace=UNDOTBS1' ] }}"
      when: first_rac_node is not defined

    - name: Init Parameter undo_tablespace
      debug:
        msg: "{{ init_undo_list | join(',') }}"


    - name: DB init parameter thread (RAC mode)
      set_fact:
        init_thread_list: "{{ init_thread_list + [ oracle_sid + ((play_hosts.index(item) + 1)|string) + '.thread=' + ((play_hosts.index(item) + 1)|string) ] }}"
      with_items: "{{ ansible_play_batch }}"
      when: first_rac_node is defined

    - name: Init Parameter undo_tablespace
      debug:
        msg: "{{ init_thread_list | join(',') }}"


    - name: DB init parameter instance_number (RAC mode)
      set_fact:
        init_instance_list: "{{ init_instance_list + [ oracle_sid + ((play_hosts.index(item) + 1)|string) + '.instance_number=' + ((play_hosts.index(item) + 1)|string) ] }}"
      with_items: "{{ ansible_play_batch }}"
      when: first_rac_node is defined

    - name: Init Parameter undo_tablespace
      debug:
        msg: "{{ init_instance_list | join(',') }}"

    - name: install db.rsp
      template:
        src: db.no.comments.rsp
        dest: /home/oracle/db.rsp
        mode: '0640'
        owner: oracle
        group: oinstall

    - name: Uncomment .rsp parameter oracle.install.db.CLUSTER_NODES
      replace:
        path: /home/oracle/db.rsp
        regexp: '^#(oracle.install.db.CLUSTER_NODES.*)'
        replace: '\1'
      when: first_rac_node is defined

    - shell: "./runInstaller -responseFile /home/oracle/db.rsp -silent -ignorePrereqFailure"
      args:
        chdir: "/oracle/u01/db/{{ oracle_ver_path }}"
        creates: "/oracle/u01/db/{{ oracle_ver_path }}/oraInst.loc"
      ignore_errors: true
      register: db_setup_out
    - debug: 
        msg: "Return code is {{ db_setup_out }}"
    - fail:
        msg: "Return code is {{ db_setup_out.rc }}"
      when: db_setup_out.rc > 6

  rescue:
    - name: delete install db.rsp
      file:
        path: /home/oracle/db.rsp
        state: absent

    - fail:
        msg: './runInstaller failed'

  become: yes
  become_user: oracle

- name: delete install db.rsp
  file:
    path: /home/oracle/db.rsp
    state: absent
