---
- copy:
    src: docker.gpg
    dest: /etc/pki/rpm-gpg/

- name: Docker GPG key
  rpm_key:
    state: present
    key: /etc/pki/rpm-gpg/docker.gpg

- name: Docker .repo
  copy:
    src: docker-ce.repo
    dest: /etc/yum.repos.d/

- name: directory /etc/docker
  file:
    path: /etc/docker
    state: directory

- name: configure docker 1/2
  copy:
    src: docker.daemon.json
    dest: /etc/docker/daemon.json

- name: create docker storagefs 1/3
  lvol:
    vg: vg01
    lv: docker
    size: 10g
    shrink: no

- name: Create /dev/vg01/docker 2/3
  filesystem:
    fstype: ext4
    dev: /dev/vg01/docker

- name: Create /dev/vg01/docker 3/3
  mount:
    path: /var/lib/docker
    src: /dev/vg01/docker
    state: mounted
    fstype: auto

- name: Ensure group "docker" exists with correct gid
  group:
    name: docker
    state: present
    gid: 901

- name: Dockerm rpm
  yum:
    name: device-mapper-persistent-data,lvm2,docker-ce
    enablerepo: docker-ce-stable

- name: directory /etc/systemd/system/docker.service.d
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
  
- name: enable and start docker
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Docker listen on localhost
  copy:
    src: docker.service.override.conf
    dest: /etc/systemd/system/docker.service.d/override.conf
  notify:
    - restart docker
