
- name: Set authorized key took from file
  authorized_key:
    user: oracle
    state: present
    key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"

- name: ensure private key and public one are present
  copy: 
    src: keys/
    dest: "/home/oracle/.ssh/"
    mode: 0400
    owner: oracle
    group: oinstall
  with_items:
    - id_rsa

- name: Accept ssh keys from all other cluster nodes
  shell: "ssh -oStrictHostKeyChecking=no {{ item }} hostname"
  become: yes
  become_user: oracle
  with_items:
    - "{{ ansible_play_batch }}"
