
- block:
    - debug:
        msg: "Unpack into {{ oracle_home }}"
    - name: Download install package {{ oracle_db_media }}
      get_url:
        url: http://192.168.8.200/oracle/{{ oracle_release }}/{{ oracle_db_media }}
        dest: "{{ oracle_install_dir_temp }}"
        mode: '0640'

    - name: unzip install package {{ oracle_db_media }}
      unarchive:
        src:  "{{ oracle_install_dir_temp }}/{{ oracle_db_media }}"
        dest: "{{ oracle_home }}"
        remote_src: yes

    - name: delete install .zip package {{ oracle_db_media }}
      file:
        path: "{{ oracle_install_dir_temp }}/{{ oracle_db_media }}"
        state: absent

  become: yes
  become_user: oracle
